"""add mode booleans to collection table

Revision ID: 0985498c8951
Revises: 7d6442462d53
Create Date: 2018-01-19 00:02:49.228853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0985498c8951'
down_revision = '7d6442462d53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collections', sa.Column('is_select_points', sa.Boolean(), server_default='0', nullable=True))
    op.add_column('collections', sa.Column('is_tags_exclusive', sa.Boolean(), server_default='0', nullable=True))
    op.add_column('collections', sa.Column('is_tags_inclusive', sa.Boolean(), server_default='0', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collections', 'is_tags_inclusive')
    op.drop_column('collections', 'is_tags_exclusive')
    op.drop_column('collections', 'is_select_points')
    # ### end Alembic commands ###
