"""remove categories table and column in points table

Revision ID: 484dda9feb6c
Revises: 8b307702f7ba
Create Date: 2017-09-27 11:23:31.872962

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '484dda9feb6c'
down_revision = '8b307702f7ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'points_ibfk_1', 'points', type_='foreignkey')
    op.drop_table('categories')
    op.drop_column('points', 'category_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('points', sa.Column('category_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key(u'points_ibfk_1', 'points', 'categories', ['category_id'], ['category_id'])
    op.create_table('categories',
    sa.Column('category_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('time_updated', mysql.TIMESTAMP(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('category_id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    # ### end Alembic commands ###
