"""rename association tables

Revision ID: 5b0c4c468e8a
Revises: ae0c6fa2a284
Create Date: 2017-09-29 21:45:09.378336

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5b0c4c468e8a'
down_revision = 'ae0c6fa2a284'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tag_collection_associations')
    op.drop_table('point_tag_associations')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('point_tag_associations',
    sa.Column('point_tag_association_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('point_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('tag_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('time_updated', mysql.TIMESTAMP(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['point_id'], [u'points.point_id'], name=u'point_tag_associations_ibfk_1'),
    sa.ForeignKeyConstraint(['tag_id'], [u'tags.tag_id'], name=u'point_tag_associations_ibfk_2'),
    sa.PrimaryKeyConstraint('point_tag_association_id', 'point_id', 'tag_id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_table('tag_collection_associations',
    sa.Column('tag_collection_association_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('tag_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('collection_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('time_updated', mysql.TIMESTAMP(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], [u'collections.collection_id'], name=u'tag_collection_associations_ibfk_2'),
    sa.ForeignKeyConstraint(['tag_id'], [u'tags.tag_id'], name=u'tag_collection_associations_ibfk_1'),
    sa.PrimaryKeyConstraint('tag_collection_association_id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    # ### end Alembic commands ###
