"""remove unused columns in association tables


Revision ID: 5c92cd81ee6c
Revises: 5b0c4c468e8a
Create Date: 2017-09-30 16:22:20.946202

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5c92cd81ee6c'
down_revision = '5b0c4c468e8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('point_tag_correlations', 'time_updated')
    op.drop_column('point_tag_correlations', 'point_tag_correlation_id')
    op.drop_column('tag_collection_correlations', 'tag_collection_correlation_id')
    op.drop_column('tag_collection_correlations', 'time_updated')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag_collection_correlations', sa.Column('time_updated', mysql.TIMESTAMP(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=True))
    op.add_column('tag_collection_correlations', sa.Column('tag_collection_correlation_id', mysql.INTEGER(display_width=11), nullable=False))
    op.add_column('point_tag_correlations', sa.Column('point_tag_correlation_id', mysql.INTEGER(display_width=11), nullable=False))
    op.add_column('point_tag_correlations', sa.Column('time_updated', mysql.TIMESTAMP(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=True))
    # ### end Alembic commands ###
