"""rename association tables

Revision ID: 7d6442462d53
Revises: 5c92cd81ee6c
Create Date: 2017-09-30 16:23:57.729296

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7d6442462d53'
down_revision = '5c92cd81ee6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('point_tag_associations',
    sa.Column('point_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['point_id'], ['points.point_id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.tag_id'], )
    )
    op.create_table('tag_collection_associations',
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.collection_id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.tag_id'], )
    )
    op.drop_table('point_tag_correlations')
    op.drop_table('tag_collection_correlations')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag_collection_correlations',
    sa.Column('tag_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('collection_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], [u'collections.collection_id'], name=u'tag_collection_correlations_ibfk_2'),
    sa.ForeignKeyConstraint(['tag_id'], [u'tags.tag_id'], name=u'tag_collection_correlations_ibfk_1'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_table('point_tag_correlations',
    sa.Column('point_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('tag_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['point_id'], [u'points.point_id'], name=u'point_tag_correlations_ibfk_1'),
    sa.ForeignKeyConstraint(['tag_id'], [u'tags.tag_id'], name=u'point_tag_correlations_ibfk_2'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('tag_collection_associations')
    op.drop_table('point_tag_associations')
    # ### end Alembic commands ###
