""""schema" > "collection" in my schema b/c schema is a reserved word in mysql

Revision ID: ae0c6fa2a284
Revises: 484dda9feb6c
Create Date: 2017-09-27 13:26:27.349163

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ae0c6fa2a284'
down_revision = '484dda9feb6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collections',
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('time_added', sa.TIMESTAMP(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('time_updated', sa.TIMESTAMP(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('collection_id')
    )
    op.create_table('tag_collection_correlations',
    sa.Column('tag_collection_correlation_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('time_updated', sa.TIMESTAMP(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.collection_id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.tag_id'], ),
    sa.PrimaryKeyConstraint('tag_collection_correlation_id')
    )
    op.drop_table('schemas')
    op.drop_table('tag_schema_correlations')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag_schema_correlations',
    sa.Column('tag_schema_correlation_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('tag_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('schema_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('time_updated', mysql.TIMESTAMP(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['schema_id'], [u'schemas.schema_id'], name=u'tag_schema_correlations_ibfk_1'),
    sa.ForeignKeyConstraint(['tag_id'], [u'tags.tag_id'], name=u'tag_schema_correlations_ibfk_2'),
    sa.PrimaryKeyConstraint('tag_schema_correlation_id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_table('schemas',
    sa.Column('schema_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('time_added', mysql.TIMESTAMP(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('time_updated', mysql.TIMESTAMP(), server_default=sa.text(u'CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('schema_id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('tag_Collection_correlations')
    op.drop_table('collections')
    # ### end Alembic commands ###
